"""Added delivery partner model

Revision ID: 0b74085fa166
Revises: 598817f7f314
Create Date: 2025-11-23 11:25:46.789690

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "0b74085fa166"
down_revision: Union[str, Sequence[str], None] = "598817f7f314"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "DeliveryPartners",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("password_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("serviceable_codes", postgresql.ARRAY(sa.INTEGER()), nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(), nullable=True),
        sa.Column("maximum_capacity", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "Sellers", sa.Column("created_at", postgresql.TIMESTAMP(), nullable=True)
    )
    op.add_column(
        "Shipments", sa.Column("created_at", postgresql.TIMESTAMP(), nullable=True)
    )
    op.add_column(
        "Shipments", sa.Column("delivery_partner_id", sa.Uuid(), nullable=False)
    )
    op.create_foreign_key(
        None, "Shipments", "DeliveryPartners", ["delivery_partner_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "Shipments", type_="foreignkey")
    op.drop_column("Shipments", "delivery_partner_id")
    op.drop_column("Shipments", "created_at")
    op.drop_column("Sellers", "created_at")
    op.drop_table("DeliveryPartners")
    # ### end Alembic commands ###
