"""Added Client contact - {client_contact_email and client_contact_phone}

Revision ID: 267917829d9f
Revises: 5a4d6fc75253
Create Date: 2026-02-05 10:18:14.015651

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '267917829d9f'
down_revision: Union[str, Sequence[str], None] = '5a4d6fc75253'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
