"""Added Client contact _ saved model before execution

Revision ID: 3cdfe7cd7ef4
Revises: 267917829d9f
Create Date: 2026-02-05 13:24:32.823750

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cdfe7cd7ef4'
down_revision: Union[str, Sequence[str], None] = '267917829d9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shipments', sa.Column('client_contact_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('Shipments', sa.Column('client_contact_phone', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Shipments', 'client_contact_phone')
    op.drop_column('Shipments', 'client_contact_email')
    # ### end Alembic commands ###
