"""fix missing contact columns

Revision ID: 50bd04e13156
Revises: 3cdfe7cd7ef4
Create Date: 2026-02-05 13:35:18.938656

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50bd04e13156'
down_revision: Union[str, Sequence[str], None] = '3cdfe7cd7ef4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Shipments', 'client_contact_phone',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Shipments', 'client_contact_phone',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
