"""adding zip code address in Sellers table

Revision ID: 598817f7f314
Revises:
Create Date: 2025-11-22 10:54:40.807686

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "598817f7f314"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Sellers",
        sa.Column("address", sa.Integer(), nullable=False, server_default="0"),
    )

    # Remove the default value 'server_default='0'' after adding the column
    # Now any time we try to add a null value in address column, PostgreSQL will throw an error.
    op.alter_column("Sellers", "address", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Sellers", "address")
    # ### end Alembic commands ###
