"""refactor_sellers_and_shipments

Revision ID: 5a4d6fc75253
Revises: 54d72e0407b7
Create Date: 2026-01-27 13:06:26.123666

"""

from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5a4d6fc75253"
down_revision: Union[str, Sequence[str], None] = "54d72e0407b7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shipment_event",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), nullable=True),
        sa.Column("location", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(name="shipmentstatus", create_type=False),
            nullable=False,
        ),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("shipment_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["shipment_id"],
            ["Shipments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("Sellers", sa.Column("zip_code", sa.Integer(), nullable=True))
    op.alter_column(
        "Sellers",
        "address",
        existing_type=sa.INTEGER(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        nullable=True,
    )
    op.drop_column("Shipments", "status")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Shipments",
        sa.Column(
            "status",
            postgresql.ENUM(
                "placed",
                "in_transit",
                "out_for_delivery",
                "delivered",
                name="shipmentstatus",
            ),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.alter_column(
        "Sellers",
        "address",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.INTEGER(),
        nullable=False,
    )
    op.drop_column("Sellers", "zip_code")
    op.drop_table("shipment_event")
    # ### end Alembic commands ###
